#!/system/bin/sh
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels ];
then
echo '24576 775' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '61440 775' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '122880 775' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '184320 775' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '192000 775' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '122000 750' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '230400 775' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '307200 775' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '384000 850' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '460800 850' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '537600 875' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '614400 875' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '691200 875' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '768000 900' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '844800 925' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '921600 925' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '998400 975' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1075200 1000' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1152000 1025' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1228800 1050' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1305600 1075' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1382400 1125' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1459200 1150' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1536000 1200' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1612800 1250' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1689600 1300' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1766400 1375' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1843200 1425' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1920000 1450' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1996800 1475' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels 
fi;
