#!/system/bin/sh
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels ];
then
echo '1996800 1475' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '24576  850' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '61440  900' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '122880  900' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '184320  900' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '192000  900' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '122000  875' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '230400  900' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '307200  900' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '384000  925' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '460800  950' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '537600  975' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '614400  975' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '691200 1000' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '768000 1025' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '844800 1025' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '921600 1050' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '998400 1050' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1075200 1075' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1152000 1075' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1228800 1100' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1305600 1175' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1382400 1200' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1459200 1225' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1536000 1300' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1612800 1350' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1689600 1400' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1766400 1425' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1843200 1450' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1920000 1475' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
fi
