#!/sbin/sh
#
# Kang-o-rama Advanced Installer Script
# Version 2.0
# By djmcnz
#
# Parameter based script to allow users to customise
# installation of Kang-o-rama. Requires configuration
# file to be present on SD card for custom options. 
# 
# Defaults to standard install without configution file.
#
# Input file = sd-fat/android/kangorama/install.cfg
#

# Initilise

B="busybox"
V=""
SDMOUNT=0
SDEXT=0
NOAPPS=0
ADWLAUNCHER=0
LAUNCHERPRO=0
STOCKFONTS=0
STOCKWIDGETS=0
STOCKDIALER=0
STOCKTRANSITIONS=0
SYSAPPS=0
NOCAR=0
APPS2EXT=0
BOOTANIMATIONS=0
FILECOUNT=0
NOWIPE=0


APPDIR='/data'
DATADIR='/data'

# Set and check all necessary mount points

  if $B test $( grep -c " /system " "/proc/mounts" ) -eq 0; then
    $B mount /system
  
    if $B test $( grep -c " /system " "/proc/mounts" ) -eq 0; then
      echo "!! Mount error - /system cound not be mounted."
      echo "!! Aborting script ROM is not installed."
      exit
    fi
  fi

  if $B test $( grep -c " /data " "/proc/mounts" ) -eq 0; then
    $B mount /data

    if $B test $( grep -c " /data " "/proc/mounts" ) -eq 0; then
      echo "!! Mount error - /data cound not be mounted."
      echo "!! Aborting script ROM is not installed."
      exit
    fi
  fi

  if $B test $( grep -c " /sd-ext " "/proc/mounts" ) -eq 0; then
    $B mount /sd-ext

    if $B test $( grep -c " /sd-ext " "/proc/mounts" ) -eq 0; then
      echo "++ SD-EXT partition could not be mounted."
      echo "++ Proceeding with normal installation."
    else
      echo "++ SD-EXT partition successfully mounted."
      SDEXT=1
    fi
  else
    echo "++ SD-EXT partition already mounted."
    SDEXT=1
  fi

  if $B test $( grep -c " /sdcard " "/proc/mounts" ) -eq 0; then
    $B mount /sdcard
    SDMOUNT=1
  else
    SDMOUNT=2
  fi

# Read Advanced Installer flags

  if [ -e "/sdcard/android/kangorama/install.cfg" ]; then
    echo "++ Advanced Installer config file found."
    cp -fr /sdcard/android/kangorama/install.cfg /tmp/kor/
    NOAPPS=$( grep -ci "noapps" "/tmp/kor/install.cfg" )
    ADWLAUNCHER=$( grep -ci "adwlauncher" "/tmp/kor/install.cfg" )
    LAUNCHERPRO=$( grep -ci "launcherpro" "/tmp/kor/install.cfg" )
    STOCKFONTS=$( grep -ci "stockfonts" "/tmp/kor/install.cfg" )
    STOCKWIDGETS=$( grep -ci "stockwidgets" "/tmp/kor/install.cfg" )
    STOCKDIALER=$( grep -ci "stockdialer" "/tmp/kor/install.cfg" )
    STOCKTRANSITIONS=$( grep -ci "stocktransitions" "/tmp/kor/install.cfg" )
    SYSAPPS=$( grep -ci "sysapps" "/tmp/kor/install.cfg" )
    NOCAR=$( grep -ci "nocar" "/tmp/kor/install.cfg" )
    APPS2EXT=$( grep -ci "apps2ext" "/tmp/kor/install.cfg" )
    BOOTANIMATIONS=$( grep -ci "bootanimations" "/tmp/kor/install.cfg" )
  fi

# Process and install custom user apps if required

  if [ $SYSAPPS -gt 0 ]; then
    cp -fr /sdcard/android/kangorama/system/*.apk /tmp/kor/system/
    FILECOUNT=$(ls -l /tmp/kor/system/*.apk | wc -l)
    cp -fr /tmp/kor/system/*.apk /system/app/
    rm -fr /tmp/kor/system/*.apk
    echo "++ $FILECOUNT user system apps installed."
    FILECOUNT=0
  fi

# Process and install custom boot animations if required

  if [ $BOOTANIMATIONS -gt 0 ]; then

    if [ $SDEXT -eq 1 ]; then
      if [ -d "/sdcard/bootanimation" ]; then
        if [ ! -d "/sd-ext/bootanimation" ]; then
          mkdir /sd-ext/bootanimation
          echo "++ SD-EXT bootanimation directory created."
        fi
        
        cp -f /sdcard/bootanimation/*.zip /tmp/kor/bootanimation/
        FILECOUNT=$(ls -l /tmp/kor/bootanimation/*.zip | wc -l)
        cp -fr /tmp/kor/bootanimation/*.zip /sd-ext/bootanimation/
        rm -fr /tmp/kor/bootanimation/*.zip
        echo "++ $FILECOUNT boot animations copied."
        FILECOUNT=0
      else
        echo "!! Random boot animation flag found but"
        echo "!! directory does not exist on /sd-fat."
      fi
    else
      echo "!! Random boot animation flag found but"
      echo "!! SD-EXT partition was not mounted."
    fi
  fi

# Delete davlik-cache

  rm -fr /data/dalvik-cache/*
  rm -fr /sd-ext/dalvik-cache/*

# Test if user has wiped and if so copy files and directories

  if [ -e "/data/system/packages.xml" ]; then
    
    cp -f /tmp/kor/system/firstboot.sh /data/local/
    
    chmod 0777 /data/local/firstboot.sh
    
    echo "++ /data partition was not wiped, upgrading."
    
    NOWIPE=1
    
  else

    cp -fr /tmp/kor/data/* /data/

    for dir in /tmp/kor/data/*; do
      V=$(basename $dir)
      chmod -R 0777 /data/$V
      find /data/$V -type d -exec chmod 0777 "{}" \;
      chown -R 1000:1000 /data/$V
      V=""
    done    

    echo dummy > /data/system/packages.xml
    
    echo "++ /data partition was wiped, full install."

  fi

# Set up Apps2SD (EXT) and determine app install location
# Default location is /data/app

  if [ $SDEXT -eq 0 ]; then
    
    if [ $APPS2EXT -gt 0 ]; then
      echo "!! apps2ext flag set but SD-EXT cound not be mounted."
      echo "!! Proceeding with internal install."
      echo "!! Please create or check SD-EXT partition after first"
      echo "!! boot and then re-enable Apps2SD."
    fi
    
  else
    
    if [ $NOWIPE -eq 1 ]; then

      if [ -L "/data/app" ]; then 
        echo "!! Symlink for /data/app detected."
        echo "!! Settings apps2ext flag. Apps2SD will be enabled."
        APPDIR='/sd-ext'
        APPS2EXT=1
      fi
    fi
    
    if [ $APPS2EXT -gt 0 ]; then    
      echo "++ Apps2SD set up to run at first boot."
    fi
  fi

# Install Kang-o-rama applications as required
# Check if app already exists on /data
# If not then install application and necessary data

  if [ $NOAPPS -gt 0 ]; then
    cp -f /tmp/kor/app/system/* /system/app/
    echo "++ Kang-o-rama apps skipped."
  else

    mv -f /tmp/kor/app/system/*.apk /tmp/kor/app/

# Check to see if the user has also moved /data/data
# If so, try and find it on /sd-ext, if it's not there
# Kill the symlinks and install to /data/data
# The user will probably lose some application data.

    if [ $NOWIPE -eq 1 ]; then

      if [ -L "/data/data" ]; then
        echo "!! Symlink for /data/data detected."
        if [ -d "/sd-ext/data" ]; then 
          echo "!! Attempting to install data to /sd-ext/data/"
          DATADIR='/sd-ext'
        else
          echo "!! Could not find /sd-ext/data/"
          echo "!! Forcing data to /data/data/, some data may be lost!"
          rm -f /data/data
          mkdir -p /data/data
        fi
      fi
    fi

    for file in /tmp/kor/app/*.apk; do
      V=$(basename $file)
      W=$(basename $V .apk)
      X="package name=\"$W\" codePath=\"/data/app/"
            
      if $B test $( grep -ci "$X" "/data/system/packages.xml" ) -gt 0; then
        echo "!! $W already exists on /data, skipping."
      else
        cp /tmp/kor/app/$V $APPDIR/app/
        chmod 0644 $APPDIR/app/$V
        chown 1000:1000 $APPDIR/app/$V
        
        if [ -e /tmp/kor/app/data/$W ]; then
          cp -fr /tmp/kor/app/data/$W $DATADIR/data/
          chmod -R 0644 $DATADIR/data/$W
          find $DATADIR/data/$W -type d -exec chmod 0777 "{}" \;
          chown -R 1000:1000 $DATADIR/data/$W
        fi
        echo "++ $W installed."
      fi
      
      X=""
      W=""
      V=""
    done

    if [ $NOWIPE -eq 0 ]; then
      rm -f /data/system/packages.xml    
    fi
    echo "++ Kang-o-rama apps installed."
  fi

# Apply custom flags

  if [ $ADWLAUNCHER -gt 0 ]; then
    rm -f /system/app/GBLauncher.apk
    cp -f /tmp/kor/launcheradw/ADWLauncher.apk /system/app/
    echo "++ ADW.Launcher installed."
  fi

  if [ $LAUNCHERPRO -gt 0 ]; then

    if [ -e "/system/app/GBLauncher.apk" ]; then
      rm -f /system/app/GBLauncher.apk
    else
      if [ -e "/system/app/ADWauncher.apk" ]; then
        rm -f /system/app/ADWLauncher.apk
        echo "!! ADW.Launcher removed. Use one launcher flag only."
      fi
    fi

    cp -f /tmp/kor/launcherpro/LauncherPro.apk /system/app/
    echo "++ LauncherPro installed."
  fi

  if [ $STOCKFONTS -gt 0 ]; then
    cp -f /tmp/kor/stockfonts/*.ttf /system/fonts/
    echo "++ Stock fonts installed."
  fi

  if [ $STOCKWIDGETS -gt 0 ]; then
    cp -f /tmp/kor/stockwidgets/*.apk /system/app/
    echo "++ Stock widgets installed."
  fi

  if [ $STOCKDIALER -gt 0 ]; then
    cp -f /tmp/kor/stockdialer/*.apk /system/app/
    echo "++ Stock phone and contacts installed."
  fi

  if [ $STOCKTRANSITIONS -gt 0 ]; then
    cp -f /tmp/kor/stocktransitions/framework-res.apk /system/framework/
    echo "++ Stock window trainsitions restored."
  fi

  if [ $NOCAR -gt 0 ]; then
    rm -f /system/app/CarHomeLauncher.apk

    if [ -e "/system/app/com.google.android.carhome.apk" ]; then
      rm -f /system/app/CalHomeLauncher.apk
    fi
    echo "++ Car dock app deleted."
  fi


# Copy logs and tidy up mounts and files
  
  cp -f /tmp/recovery.log /data/local/korinstall.log
  ls -lR /data > /tmp/kor/kormodes.log
  cp -f /tmp/kor/kormodes.log /data/local/kormodes.log

  if [ $SDMOUNT -eq 1 ]; then
    $B umount /sdcard
    SDMOUNT=0
  fi

  if [ $SDEXT -eq 1 ]; then
    $B umount /sd-ext
    SDEXT=0
  fi
  
  $B umount /data
  $B umount /system

  rm -fr /tmp/kor
  echo "++ Script completed."
exit
