#!/system/bin/sh
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels ];
then
echo '122000 875' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '230400 900' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '307200 900' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '384000 900' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '460800 925' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '537600 950' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '614400 950' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '691200 975' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '768000 1000' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '844800 1000' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '921600 1025' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '998400 1025' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1075200 1050' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1152000 1050' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1228800 1075' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1305600 1150' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1382400 1175' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1459200 1200' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1536000 1275' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1612800 1325' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1689600 1375' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1766400 1400' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1843200 1425' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1920000 1450' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo '1996800 1500' > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels 
fi;
